pipeline {
  agent any

  options {
    timeout(time: 2, unit: 'MINUTES')
  }
  
  environment {
      TAG = VersionNumber (versionNumberString: '${BRANCH_NAME}.${BUILD_DATE_FORMATTED, "yyyyMMdd"}.${BUILD_NUMBER}')
  }

  stages {
    
 
    stage('Install dependecies') {
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '*/main'], [name: '*/develop']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/jhonNP/app-devco.git']]])
        nodejs('nodev17.7.2') {
            sh "npm install"
        }
      }
    }
    stage('Run tests') {
      steps {
        nodejs('nodev17.7.2') {
            sh "npm run test -- --no-watch"
        }
      }
    }

    stage('Build develop') {
       when {
            branch "develop"
       }
      steps {
        nodejs('nodev17.7.2') {
            sh "npm run build:dev"
            sh "zip -r ${TAG}.zip dist/my-app-devco/"
        }

      }
    }

    stage('Build pdn') {
      when {
            branch "master"
      }
      steps {
        nodejs('nodev17.7.2') {
            sh "npm run build:prod"
        }
      }

    }
    stage('compress build') {
      steps {
        sh "zip -r ${TAG}.zip dist/my-app-devco/"
       }
    }
  }
}

